import { publicRouter } from '@manablox/api-public';
import { router } from '@manablox/api-rpc';
import { pluginRpcKit } from '@manablox/api-rpc/plugin';
import { ERROR_KEYS, type ManabloxPlugin, pluginId, TRANSFORM_HOOKS } from '@manablox/core';
import { HOOK_DOCS, type HookDocSection } from '@manablox/core/hook-docs';
import { generateOpenApiDocument } from '@manablox/server';

/**
 * The reference pages derived from the code, by path under the output folder: the error
 * keys and the HTTP API (the core's and every plugin's of the instance), and the hooks.
 */
export async function referencePages(
  plugins: readonly ManabloxPlugin[],
): Promise<Record<string, string>> {
  return {
    'reference/errors.md': errorsPage(plugins),
    'extending/hooks.md': hooksPage(HOOK_DOCS),
    'reference/http-api.md': await apiPage(plugins),
  };
}

const GENERATED = '<!-- Generated by `manablox docs generate`; edit the source, not this file. -->';

function page(title: string, description: string, body: string): string {
  return `---\ntitle: '${title}'\ndescription: '${description}'\n---\n\n${GENERATED}\n\n${body.trim()}\n`;
}

// Error keys

function errorsPage(plugins: readonly ManabloxPlugin[]): string {
  const groups = new Map<string, string[]>();
  for (const key of ERROR_KEYS) {
    const group = key.split('.')[0] as string;
    groups.set(group, [...(groups.get(group) ?? []), key]);
  }

  const sections = [...groups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([group, keys]) => `### \`${group}\`\n\n${keys.map((key) => `- \`${key}\``).join('\n')}`)
    .join('\n\n');
  const pluginSections = plugins
    .filter((plugin) => Object.keys(plugin.errors ?? {}).length)
    .map(
      (plugin) =>
        `### \`plugins.${pluginId(plugin.name)}\`\n\n${Object.entries(plugin.errors ?? {})
          .map(([key, spec]) => `- \`${key}\`: ${spec.message}`)
          .join('\n')}`,
    )
    .join('\n\n');

  return page(
    'Error keys',
    'Every error key the platform raises, for translating messages and matching on failures.',
    `
Every error the platform raises carries a *key* (an identifier like
\`content.slug.duplicate\`) plus a \`kind\`, an HTTP status, and a list of *details*, each
with its own key, an optional path into the input (\`['fields', 2, 'value']\`) and
interpolation params. The key is what a client translates; the admin's sentences live in
[\`@manablox/admin-sdk\`](https://github.com/manablox/manablox-cms/blob/main/packages/admin-sdk/src/lib/messages.ts),
and the SDK exposes keys unchanged.

| Kind | Status | Meaning |
| --- | --- | --- |
| \`validation\` | 422 | The input was understood and refused; the details say where. |
| \`bad_request\` | 400 | The request cannot be acted on as stated. |
| \`unauthorized\` | 401 | No principal. |
| \`forbidden\` | 403 | A principal without the permission. |
| \`not_found\` | 404 | The named thing does not exist, or is not visible to the caller. |
| \`conflict\` | 409 | The write collides with the current state: a stale version, a duplicate. |
| \`too_large\` | 413 | The body is larger than the limit, e.g. an upload past the file size limit. |
| \`rate_limited\` | 429 | Too many requests; wait for the \`retry-after\` header. |
| \`unavailable\` | 503 | The instance cannot serve yet, e.g. a public API with no space to serve. |
| \`internal\` | 500 | A bug or an outage. Masked on a public instance. |

## The error body

Every surface sends the same object:

\`\`\`json
{
  "key": "validation.failed",
  "kind": "validation",
  "status": 422,
  "message": "validation.failed",
  "details": [
    { "key": "validation.invalid", "path": ["limit"], "params": { "code": "too_big", "maximum": 100 } }
  ]
}
\`\`\`

\`message\` repeats the key, except for an unexpected error, which is always
\`{ "key": "internal.error", "kind": "internal", "status": 500 }\` with a fixed English
message and no details. On the public instance an \`internal\` error also drops its details.
Input that fails the schema of a procedure is \`validation.failed\` with one
\`validation.invalid\` detail per problem; its params carry the schema message and, when
known, \`code\`, \`origin\`, \`expected\`, \`minimum\` and \`maximum\`.

Where it travels:

| Surface | Carrier |
| --- | --- |
| REST (\`/v1\`, \`/api/v1\`), uploads, media, transfer, rate limits, unmatched paths | The response body \`{ "error": { ... } }\`, at \`status\`. |
| oRPC (\`/rpc\`) | The oRPC error: \`code\` from the kind, \`message\`, and the whole object as \`data\`. |
| GraphQL (\`/graphql\`) | Each entry of \`errors\`: \`message\`, plus \`extensions\` with \`key\`, \`kind\`, \`status\` and \`details\`. The HTTP status rules are in [GraphQL](../delivery/graphql.md#errors-and-http-status). |

An unmatched path answers \`route.notFound\` and a missing media file \`asset.notFound\` to a
client that accepts JSON (API paths always do); a browser or an image load gets a plain
text 404 instead.

GraphQL masking hides only unexpected errors: a \`ManabloxError\` such as an unknown
\`type\` argument keeps its key on a masked instance, while anything else reads
\`Unexpected error.\` with no key.

The catalogue is \`ERROR_KEYS\` of \`@manablox/core\`
([source](https://github.com/manablox/manablox-cms/blob/main/packages/core/src/error-keys.ts));
the \`ManabloxError\` factories and the validation collector only accept keys listed there. Field types report their own issue keys
through their value schemas; those pass through untyped and are not listed here.

## Keys

${sections}

## Plugin keys

Plugins declare keys of their own under \`plugins.<id>\`, with an English sentence each. The
plugins of the default instance:

${pluginSections}
`,
  );
}

// Hooks

function hooksPage(sections: readonly HookDocSection[]): string {
  const tables = sections
    .map((section) => {
      const rows = section.hooks.map((hook) => {
        const transforms = (TRANSFORM_HOOKS as readonly string[]).includes(hook.name)
          ? 'yes'
          : 'no';
        return `| \`${hook.name}\` | \`${hook.payload.replaceAll('|', '\\|')}\` | \`${hook.context}\` | ${transforms} |`;
      });
      return `### ${capitalise(section.title.replace(/\s+-\s.*$/, ''))}\n\n| Hook | Payload | Context | Transforms |\n| --- | --- | --- | --- |\n${rows.join('\n')}`;
    })
    .join('\n\n');

  return page(
    'Hooks',
    'The hook surface: every hook, its payload and context, and whether a handler may replace the payload.',
    `
Hooks are awaited in priority order. On a hook the table marks as transforming, a handler
may return a new payload, which replaces the one later handlers and the operation itself
see. On the other hooks the return value is ignored: a \`before...\` handler refuses the
operation by throwing, and \`after...\` handlers observe. Register them from a plugin (see [Plugins](./plugins.md#hooks)) or with
\`manablox.hooks.on(name, handler, { priority, source })\`.

Context types: \`HookContextBase\` carries the instance and, for request-scoped hooks, the
actor and space, and \`environmentId\`, the space environment the hook runs for where one
applies; \`ContentHookContext\` adds the content type; \`FieldHookContext\` adds
the field. \`ContentWriteInput\` is the validated save payload; \`ContentRecord\` a stored
row. All are exported from \`@manablox/core\`.

Unpublishing a document also unpublishes its published descendants: \`content:afterUnpublish\`
runs once for each of them, after the one for the document itself, while
\`content:beforeUnpublish\` runs for the document only. Deleting a document with its children
runs \`content:afterDelete\` the same way, once for each deleted descendant.
After the per row hooks, \`content:afterUnpublishMany\` and \`content:afterDeleteMany\` run
once per operation with every affected row, the target document first; their
\`ContentManyHookContext\` carries \`spaceId\`, \`actor\` and \`rootId\`. Rows may span types,
so resolve each through \`manablox.contentTypes\`. A handler that queries per row is better
placed on these.

Writes that touch several rows commit as one: a duplicated subtree, a folder in every
locale, a plan of content types, a space with its basic setup, several new members at once.
The \`after...\` hooks of such a write, and of every single write, run once it has committed,
so a failed write runs none of them. The built-in cleanup (menu entries, tags and the home
nomination of deleted documents, asset usages, closing an open approval on publish) runs
inside the transaction instead, before the plugin hooks, and commits or rolls back with the
write.

Content write hooks carry \`services\` in their context: \`repos\` and \`content\` bound to the
write (the type, \`HookServices\`, is filled in by \`@manablox/services\`). Inside a larger
write the \`before...\` hooks run while its transaction is open, and \`services\` write through
it, so what a handler writes commits or rolls back with the write. A handler that writes
must use them: services held elsewhere wait for the transaction to end, which blocks on
SQLite and holds locks on Postgres. Outside a transaction, and in \`after...\` hooks,
\`services\` are the root ones.

\`content:beforeRead\` runs when one document is read by id, before the row loads; its context
carries \`spaceId\`, \`actor\` and \`published\` but no type, and a handler throws to refuse the
read. \`content:beforeList\` runs before a list page, a tree, a level of children, a filter
relation or a menu loads; its \`ContentListRequest\` payload names the \`kind\` of read, the
\`typeIds\` it is limited to (empty for any type), the \`locale\` and, per kind, \`parentId\`,
\`fieldId\` or \`menu\`. Its context carries \`spaceId\`, \`actor\` and \`published\`, and a
handler throws to refuse the whole read. \`content:afterList\` runs once per \`list\` page
after \`content:afterReadMany\`.
\`field:beforeValidate\` runs on every field of the type and of each block before validation; an
absent field arrives as \`undefined\` and a returned value supplies it. \`field:afterRead\` runs
on each top level field of a read row, before \`content:afterRead\` and before fields the actor
may not read are removed.

The delivery APIs (REST and GraphQL) run the same read hooks on every document they
return: lists, lookups by id or permalink, relations, filter relations, children, menu
entries and templates. Their context has a \`null\` actor, and \`published\` is \`false\` only in
preview. A row a hook drops reads as missing there too. They run \`content:beforeRead\` for
a document asked for by id (before the row loads) or by permalink (once the path resolves,
with the found id), and \`content:beforeList\` for lists, children, filter relations and
menus. A handler that throws refuses the read: a single read answers 404
\`content.notFound\` in REST and a \`null\` field with that error in GraphQL; a refused list
or relation comes back empty and a refused menu as missing. A thrown \`ManabloxError\` keeps
its own key and status. Each hook is skipped when no handler is registered, so unused hooks
cost nothing.

Rows read from the published projection carry \`searchText: null\` (the \`search\` vector
too): delivery filters on these columns but does not return them. Draft reads (preview and
the management API) keep \`searchText\`.

\`contentType:beforeCreate\` and \`contentType:beforeUpdate\` run ahead of validation, so the
returned input is validated and stored; \`ContentTypeUpdateHookContext\` adds \`previous\`, the
type before the write. \`asset:beforeUpload\` runs after the size and type checks, with the
detected mime type; the returned \`filename\` is stored, and a handler throws to reject the
upload.

\`space:beforeCreate\` runs before a space is created or imported, with the input or the
export's space. \`member:beforeGrant\` runs before a role is granted or changed, also for the
owner of a new or imported space and for the first account, which becomes owner of every
space (a space whose handler refuses is skipped and logged); \`previous\` is the prior role or
\`null\`. \`space:beforeLocalesChange\` runs when an update changes a space's locales.
\`apiKey:beforeIssue\`, \`menu:beforeCreate\` and \`redirect:beforeCreate\` run before the row
is written.
\`redirect:beforeCreate\` carries \`source\`: \`manual\`, or \`auto\` for the redirect a publish
records when a permalink moved; a refused automatic redirect is skipped and logged, and the
publish goes on.
A handler throws to refuse; a thrown \`ManabloxError\` keeps its key and status. A space
import runs \`menu:beforeCreate\` and \`redirect:beforeCreate\` for each row it restores, before
it writes anything, and data providers' checks after them (the workflows plugin runs
\`workflows:beforeEnable\` there, the webhooks plugin \`webhooks:beforeCreate\`), so a refusal
leaves no space behind; hooks without a handler are skipped. Plugins declare hooks of their own
as \`<id>:<event>\`: the workflows plugin's are in [Workflows](../admin/workflows.md#hooks), the
webhooks plugin's in [Webhooks](../admin/webhooks.md#hooks), the website plugin's in
[Forms and links](../site/forms-links.md).

\`asset:afterDelete\`, \`mail:afterSend\` and \`request:served\` only observe: a handler that
throws is logged and the operation goes on. \`asset:afterDelete\` runs once an asset and its
files are gone; \`size\` includes the variants, except for assets removed with their last
space, where it is the original only. \`mail:afterSend\` runs per sent mail, for notifications
and the mail actions of workflows; \`kind\` names the sender (\`notification\`, or what a
plugin that sends mail passes, e.g. \`workflows\`) and \`transport\` is \`account\` for mail sent
through an editor's own account. \`request:served\` (\`RequestServed\`: \`surface\`, \`spaceId\`, \`status\`,
\`bytes\`, \`cached\`) runs after responses of the delivery APIs (GraphQL
and \`/v1\`), of \`/api/v1\` reads and GraphQL requests made with an API key (surface
\`management\`), of media and of plugin modes, whose surface is the mode's name (\`website\`). It never delays the response: \`bytes\` is the
\`content-length\`, else counted while the body streams out, and the hook runs once the body
was sent. \`cached\` marks answers from the response cache and \`304\` answers. With no
handler registered nothing is measured.

${tables}
`,
  );
}

function capitalise(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

// HTTP APIs

interface OpenApiDocument {
  paths?: Record<
    string,
    Record<
      string,
      {
        summary?: string;
        description?: string;
        tags?: string[];
        requestBody?: { content?: Record<string, { schema?: JsonSchema }> };
        parameters?: Array<{ name: string; in: string; required?: boolean }>;
      }
    >
  >;
}

interface JsonSchema {
  properties?: Record<string, JsonSchema & { description?: string }>;
  required?: string[];
  type?: string;
}

async function apiTable(target: object, prefix: string, info: { title: string }): Promise<string> {
  const document = (await generateOpenApiDocument(target, {
    info: { ...info, version: '1.0.0' },
  })) as OpenApiDocument;

  const rows: string[] = [];
  for (const [path, methods] of Object.entries(document.paths ?? {}).sort()) {
    for (const [method, operation] of Object.entries(methods)) {
      const body = operation.requestBody?.content?.['application/json']?.schema;
      const params = (operation.parameters ?? []).map(
        (parameter) => `${parameter.name}${parameter.required ? '' : '?'}`,
      );
      const fields = Object.keys(body?.properties ?? {}).map(
        (name) => `${name}${body?.required?.includes(name) ? '' : '?'}`,
      );
      const input = [...params, ...fields].map((name) => `\`${name}\``).join(', ') || '';
      const summary = operation.summary ?? operation.description ?? '';
      rows.push(`| \`${method.toUpperCase()}\` | \`${prefix}${path}\` | ${input} | ${summary} |`);
    }
  }
  return `| Method | Path | Input | Summary |\n| --- | --- | --- | --- |\n${rows.join('\n')}`;
}

/** The procedures of every plugin of the instance that has a router. */
async function pluginTables(plugins: readonly ManabloxPlugin[]): Promise<string> {
  const out: string[] = [];
  for (const plugin of plugins) {
    if (!plugin.rpc) continue;
    const id = pluginId(plugin.name);
    const table = await apiTable(plugin.rpc(pluginRpcKit(plugin)), `/api/v1/plugins/${id}`, {
      title: `Manablox ${id} plugin`,
    });
    out.push(`### \`${id}\`\n\n${table}`);
  }
  return out.join('\n\n');
}

async function apiPage(plugins: readonly ManabloxPlugin[]): Promise<string> {
  return page(
    'HTTP API reference',
    'Every management and delivery endpoint, generated from the routers.',
    `
Both APIs are oRPC routers, so each also serves an OpenAPI document at \`/openapi.json\` on
its instance, the source of the tables below. The management procedures are mounted twice:
as oRPC under \`/rpc\` for the admin's typed client, and as REST under \`/api/v1\`. A REST error
answers \`{ "error": { key, kind, status, message, details } }\`, and oRPC carries the same
object as the error's \`data\`; see [the error body](./errors.md#the-error-body). Both OpenAPI
documents declare this body once, as the \`Error\` schema, and reference it from the 400, 401,
403, 404, 409, 422, 429 and 500 responses of every operation. Unmatched paths answer
\`route.notFound\` in the same body to JSON clients.

## Management API (\`/api/v1\`)

Authenticated with the session cookie or an \`x-api-key\` header. Space-scoped procedures
take a \`spaceId\`; the caller needs the permission in that space. See
[Users and roles](../admin/users-and-roles.md) for what each role may do.

They read and write one environment of the space: the one \`environment\` names (its
technical name, e.g. \`staging\`), else the \`x-manablox-environment\` header, else
production. An unknown name answers 404 \`environment.notFound\`; another environment than
production needs the \`environments\` feature (403 \`control.feature\`); an API key limited
to other environments answers 403 \`environment.forbidden\`. An id of another environment's
record answers as missing. The \`environments\` procedures name the environment they
manage and take no other one.

${await apiTable(router, '/api/v1', { title: 'Manablox Management API' })}

## Delivery API (\`/v1\`)

Anonymous and read-only, served by the public instance, which is pinned to one space.
See [The public API](../delivery/public-api.md) and [REST](../delivery/rest.md).

${await apiTable(publicRouter, '/v1', { title: 'Manablox Delivery API' })}

## Plugin procedures (\`/api/v1/plugins/<id>\`)

A plugin's router answers under \`plugins.<id>\` of the management API, with the same
authentication, environments and error body. While the plugin is off for the instance or the
space it answers 404 \`route.notFound\` when hidden and 403 \`control.feature\` when locked (a
premium plugin without a license, say). The plugins of the default instance:

${await pluginTables(plugins)}
`,
  );
}
