#!/usr/bin/env node
// Writes `src/hook-docs.ts`: the hooks of `ManabloxHooks` (`src/hook-map.ts`) as data, a
// section per `// Section` comment and one entry per hook, for the hooks reference that
// `manablox docs generate` writes. The hook map is a type, so it is read from the source.
// Runs before every build; `--check` fails when the file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(pkg, 'src/hook-map.ts');
const TARGET = join(pkg, 'src/hook-docs.ts');

/** The sections of the `ManabloxHooks` interface in `source`, each with its hooks. */
function hookSections(source) {
  const body = source.slice(source.indexOf('export interface ManabloxHooks'));
  const sections = [];
  // An entry may span lines; its doc comments are dropped.
  let pending = null;
  for (const line of body.split('\n')) {
    const heading = /^\s*\/\/\s*(.+)$/.exec(line);
    if (heading && pending === null) {
      sections.push({ title: heading[1], hooks: [] });
      continue;
    }
    if (pending === null && !/^\s*'[^']+':\s*\[/.test(line)) continue;
    pending = `${pending ?? ''} ${line.replace(/\/\*\*.*?\*\//g, '')}`;
    if (!/\];\s*$/.test(line)) continue;
    const joined = pending.replace(/\s+/g, ' ').replace(/;\s*}/g, ' }').trim();
    pending = null;
    const entry = /^'([^']+)':\s*\[\s*(.+?),\s*(\w+),?\s*\];$/.exec(joined);
    if (entry)
      sections.at(-1)?.hooks.push({ name: entry[1], payload: entry[2], context: entry[3] });
  }
  return sections.filter((section) => section.hooks.length);
}

function render(sections) {
  const lines = sections.map(
    (section) =>
      `  {\n    title: ${JSON.stringify(section.title)},\n    hooks: [\n${section.hooks
        .map(
          (hook) =>
            `      { name: ${JSON.stringify(hook.name)}, payload: ${JSON.stringify(hook.payload)}, context: ${JSON.stringify(hook.context)} },`,
        )
        .join('\n')}\n    ],\n  },`,
  );
  return `// Generated by \`scripts/hook-docs.mjs\` from \`hook-map.ts\`; edit the hook map, not this file.

/** One hook of \`ManabloxHooks\`: its name and the source text of its payload and context types. */
export interface HookDoc {
  name: string;
  payload: string;
  context: string;
}

/** A section of \`ManabloxHooks\` (its \`// Section\` comment) with its hooks. */
export interface HookDocSection {
  title: string;
  hooks: readonly HookDoc[];
}

/** Every hook of \`ManabloxHooks\` by section, in source order. */
// biome-ignore format: generated
export const HOOK_DOCS: readonly HookDocSection[] = [
${lines.join('\n')}
];
`;
}

const next = render(hookSections(readFileSync(SOURCE, 'utf8')));
let current = '';
try {
  current = readFileSync(TARGET, 'utf8');
} catch {}

if (process.argv.includes('--check')) {
  if (current !== next) {
    process.stderr.write('src/hook-docs.ts is stale; run `pnpm --filter @manablox/core hooks`\n');
    process.exit(1);
  }
} else if (current !== next) {
  writeFileSync(TARGET, next);
}
