import type { PluginErrorSpec } from './plugin-extensions.js';

/** Every i18n error key the platform raises. Field-type schema keys pass through untyped. */
export const ERROR_KEYS = [
  'validation.failed',
  'validation.invalid',
  'internal.error',
  'rateLimit.exceeded',

  'control.feature',
  'control.limit',
  'control.usage',
  'control.readOnly',
  'control.suspended',
  'control.key.unknown',
  'control.scope.notAllowed',
  'control.value.invalid',
  'control.key.duplicate',
  'control.scope.invalid',
  'control.ipNotAllowed',
  'control.idempotency.mismatch',
  'control.owner.exists',
  'spaceGroup.notFound',
  'spaceGroup.externalId.taken',
  'request.invalid',
  'route.notFound',
  'service.unavailable',

  'auth.unauthorized',
  'auth.tooManyAttempts',

  'config.invalid',
  'config.scope.unknown',
  'config.mode.unknown',
  'config.port.invalid',
  'config.cache.syncIntervalInvalid',
  'config.mail.driverUnknown',
  'config.mail.optionMissing',
  'config.database.urlMissing',
  'config.database.urlUnsupported',
  'config.auth.secretMissing',
  'config.admin.notFound',
  'config.cors.credentialedWildcard',
  'config.control.keyMissing',
  'config.control.webhookUrlInvalid',
  'config.control.webhookSecretMissing',
  'config.control.allowedIpInvalid',
  'config.server.trustedProxyInvalid',

  'auth.forbidden',
  'auth.superadminRequired',
  'auth.signUp.closed',
  'auth.mail.notConfigured',
  'auth.mails.tooMany',
  'auth.email.unverified',
  'auth.email.tokenInvalid',
  'auth.twoFactor.enrolmentRequired',
  'auth.twoFactor.policyNeedsFeature',
  'auth.twoFactor.required',
  'auth.sso.required',
  'auth.sso.disabled',
  'auth.sso.unknown',
  'auth.sso.domain',
  'auth.sso.banned',
  'auth.sso.noAccount',
  'auth.sso.seats',

  'audit.notFound',
  'audit.append.failed',

  'apiKey.create.failed',

  'asset.notFound',
  'asset.create.failed',
  'asset.file.required',
  'asset.file.single',
  'asset.mimeType.notAllowed',
  'asset.tooLarge',
  'asset.notAnImage',
  'asset.crop.outOfBounds',
  'asset.focalPoint.outOfBounds',
  'asset.schedule.invalidWindow',
  'asset.spaces.required',
  'asset.spaces.forbidden',
  'assetVariant.create.failed',

  'content.validation.failed',
  'content.notFound',
  'content.notInSpace',
  'content.create.failed',
  'content.title.required',
  'content.slug.required',
  'content.slug.duplicate',
  'content.parent.notFound',
  'content.parent.notInSpace',
  'content.parent.otherLocale',
  'content.parent.self',
  'content.parent.cycle',
  'content.parent.isData',
  'content.data.hasParent',
  'content.block.type.notFound',
  'content.block.type.notABlock',
  'content.blocks.tooDeep',
  'content.translation.exists',
  'content.translation.sameLocale',
  'content.type.isBlock',
  'content.folder.typeMissing',
  'content.type.notPublishable',
  'content.schedule.invalidWindow',
  'content.schedule.notPublishable',
  'content.code.immutable',
  'content.version.conflict',
  'content.version.notFound',
  'content.approval.notRequired',
  'content.approval.alreadyPending',
  'content.approval.notPending',
  'content.approval.notRequester',
  'content.approval.create.failed',

  'contentType.validation.failed',
  'contentType.notFound',
  'contentType.create.failed',
  'contentType.inUse',
  'contentType.code.immutable',
  'contentType.name.invalid',
  'contentType.name.duplicate',
  'contentType.graphqlName.duplicate',
  'contentType.block.flagsNotAllowed',
  'contentType.plugin.unknown',
  'contentType.plugin.invalid',
  'contentType.data.flagsNotAllowed',
  'contentType.field.notFound',
  'contentType.field.name.invalid',
  'contentType.field.name.duplicate',
  'contentType.field.name.immutable',
  'contentType.field.type.notFound',
  'contentType.field.blockType.notFound',
  'contentType.field.blockType.notABlock',
  'contentType.field.subFields.tooDeep',
  'contentType.plan.empty',
  'contentType.plan.name.duplicate',
  'contentType.plan.reference.unknown',
  'contentType.plan.reference.wrongKind',

  'field.required',
  'field.unique',
  'field.databag.notFound',
  'fieldType.notFound',
  'fieldType.name.invalid',
  'fieldType.name.duplicate',

  'graphql.query.tooDeep',
  'graphql.query.tooComplex',
  'graphql.introspection.disabled',
  'graphql.persisted.required',
  'graphql.persisted.notFound',

  'media.notAnImage',
  'media.format.unsupported',
  'media.preset.notFound',
  'media.signature.invalid',

  'plugin.extend.contentType.notFound',
  'plugin.id.duplicate',
  'plugin.id.reserved',
  'plugin.requires.missing',
  'plugin.requires.cycle',
  'plugin.contribution.unknown',
  'plugin.space.required',
  'plugin.key.invalid',
  'plugin.key.duplicate',
  'plugin.rpc.unguarded',

  'publicApi.space.notFound',
  'publicApi.space.unresolved',
  'publicApi.host.unknown',
  'publicApi.schema.notReadOnly',
  'publicApi.scope.managementOnly',

  'query.field.unknown',
  'query.operator.unsupported',
  'query.sort.unsupported',
  'query.value.expectedArray',
  'query.value.expectedNumber',
  'query.limit.invalid',
  'query.offset.invalid',

  'space.validation.failed',
  'space.notFound',

  'tag.notFound',
  'tag.name.required',
  'tag.name.taken',
  'tag.merge.sameTag',

  'environment.create.failed',
  'environment.notFound',
  'environment.machineName.invalid',
  'environment.machineName.taken',
  'environment.production.undeletable',
  'environment.promote.notStaging',
  'environment.promote.confirmRequired',
  'environment.promote.failed',
  'environment.unsupported',
  'environment.forbidden',

  'menu.create.failed',
  'menu.notFound',
  'menu.validation.failed',
  'menu.machineName.taken',
  'menu.item.targetRequired',
  'menu.item.linkNeedsLabel',
  'menu.item.contentNotFound',
  'menu.item.typeNotAllowed',
  'space.create.failed',
  'space.machineName.taken',
  'space.defaultLocale.notInLocales',
  'space.plugin.unknown',
  'space.plugin.off',
  'space.plugin.invalid',
  'space.member.lastOwner',
  'space.member.roleNotFound',
  'space.assets.mimeType.outsideInstance',
  'space.assets.mimeType.outsideControl',
  'space.assets.maxFileSize.aboveInstance',
  'space.assets.maxFileSize.aboveControl',
  'space.import.exists',
  'space.import.notAnExport',
  'space.import.tooLarge',
  'space.import.assetsRefused',
  'space.import.versionUnsupported',
  'space.import.typeMissing',
  'space.import.failed',
  'space.import.notResumable',
  'space.import.running',
  'space.importing',
  'snapshot.notFound',
  'snapshot.unsupported',
  'snapshot.confirmMismatch',
  'snapshot.ownerOnly',
  'space.starter.typeTaken',

  'apiHost.notFound',
  'apiHost.validation.failed',
  'apiHost.hostname.invalid',
  'apiHost.hostname.taken',
  'redirect.notFound',
  'redirect.validation.failed',
  'redirect.path.invalid',
  'redirect.target.required',
  'redirect.target.self',
  'redirect.target.loop',
  'redirect.fromPath.taken',
  'redirect.locale.unknown',

  'storage.driver.notFound',
  'storage.key.traversal',
  'storage.local.configMissing',
  'storage.s3.configMissing',

  'apiKey.validation.failed',
  'role.validation.failed',
  'role.notFound',
  'role.create.failed',
  'role.inUse',
  'role.name.required',
  'role.machineName.invalid',
  'role.machineName.reserved',
  'role.machineName.taken',
  'role.permission.unknown',

  'mail.notConfigured',
  'mail.tokenMissing',
  'mail.serviceStatus',
  'push.notConfigured',
  'push.subscriptionInvalid',
  'push.subscription.createFailed',
  'net.blocked',
  'net.tooLarge',
  'net.tooManyRedirects',
  'secret.keyMissing',
  'secret.undecryptable',

  'credential.validation.failed',
  'credential.notFound',
  'credential.name.required',
  'credential.slug.invalid',
  'credential.slug.taken',
  'credential.kind.unknown',
  'credential.field.required',
  'credential.oauth.exchangeFailed',
  'credential.code.immutable',
  'credential.create.failed',

  'user.validation.failed',
  'user.notFound',
  'user.create.failed',
  'user.email.taken',
  'user.self.protected',
  'user.lastSuperadmin',
  'user.password.incorrect',
  'user.password.sameAsCurrent',
  'user.email.same',

  'invitation.notFound',
  'invitation.invalid',
  'invitation.expired',
  'invitation.grants.required',
  'invitation.grant.duplicate',
  'invitation.role.unknown',
  'invitation.space.notFound',
  'invitation.signInRequired',
  'invitation.emailMismatch',

  'sso.notFound',
  'sso.validation.failed',
  'sso.providerId.invalid',
  'sso.providerId.taken',
  'sso.protocol.required',
  'sso.url.invalid',
  'sso.clientId.required',
  'sso.clientSecret.required',
  'sso.discovery.failed',
  'sso.certificate.invalid',
  'sso.entityId.required',
  'sso.domains.required',
  'sso.domain.invalid',
  'sso.domain.taken',
  'sso.landingPath.invalid',

  'notification.notFound',

  // Resources declared in a config file or a plugin, and the sync that writes them.
  'codeResource.slug.invalid',
  'codeResource.duplicate',
  'codeResource.ref.unresolved',
  'codeCredential.field.unknown',
  'codeTemplate.blocks.required',
] as const;

/** An error key a plugin declares, `plugins.<id>.<name>`. */
export type PluginErrorKey = `plugins.${string}`;

export type ErrorKey = (typeof ERROR_KEYS)[number] | PluginErrorKey;

/** A core key; plugin keys are checked with `pluginErrorSpec`. */
export function isErrorKey(value: string): value is ErrorKey {
  return (ERROR_KEYS as readonly string[]).includes(value);
}

const pluginErrors = new Map<string, { plugin: string; spec: PluginErrorSpec }>();

/** Replaces one plugin's error keys; checked by `resolveConfig`. */
export function setPluginErrors(
  id: string,
  errors: Readonly<Record<string, PluginErrorSpec>>,
): void {
  for (const [key, found] of pluginErrors) if (found.plugin === id) pluginErrors.delete(key);
  for (const [key, spec] of Object.entries(errors)) pluginErrors.set(key, { plugin: id, spec });
}

/** The spec of a registered plugin error key. */
export function pluginErrorSpec(key: string): PluginErrorSpec | null {
  return pluginErrors.get(key)?.spec ?? null;
}

/** Every registered plugin error key with its English sentence. */
export function pluginErrorMessages(): Record<string, string> {
  return Object.fromEntries([...pluginErrors].map(([key, { spec }]) => [key, spec.message]));
}
