// Generated by `scripts/hook-docs.mjs` from `hook-map.ts`; edit the hook map, not this file.

/** One hook of `ManabloxHooks`: its name and the source text of its payload and context types. */
export interface HookDoc {
  name: string;
  payload: string;
  context: string;
}

/** A section of `ManabloxHooks` (its `// Section` comment) with its hooks. */
export interface HookDocSection {
  title: string;
  hooks: readonly HookDoc[];
}

/** Every hook of `ManabloxHooks` by section, in source order. */
// biome-ignore format: generated
export const HOOK_DOCS: readonly HookDocSection[] = [
  {
    title: "lifecycle",
    hooks: [
      { name: "before:init", payload: "undefined", context: "HookContextBase" },
      { name: "after:init", payload: "undefined", context: "HookContextBase" },
      { name: "before:start", payload: "undefined", context: "HookContextBase" },
      { name: "after:start", payload: "undefined", context: "HookContextBase" },
      { name: "before:stop", payload: "undefined", context: "HookContextBase" },
    ],
  },
  {
    title: "registry",
    hooks: [
      { name: "registry:contentTypes", payload: "ContentTypeDefinition[]", context: "HookContextBase" },
      { name: "registry:afterReload", payload: "{ synced: boolean; spaceId?: string | null }", context: "HookContextBase" },
    ],
  },
  {
    title: "content write path",
    hooks: [
      { name: "content:beforeValidate", payload: "ContentWriteInput", context: "ContentHookContext" },
      { name: "content:beforeCreate", payload: "ContentWriteInput", context: "ContentHookContext" },
      { name: "content:afterCreate", payload: "ContentRecord", context: "ContentHookContext" },
      { name: "content:beforeUpdate", payload: "ContentWriteInput", context: "ContentHookContext" },
      { name: "content:afterUpdate", payload: "ContentRecord", context: "ContentHookContext" },
      { name: "content:beforeDelete", payload: "{ id: string }", context: "ContentHookContext" },
      { name: "content:afterDelete", payload: "{ id: string; record: ContentRecord }", context: "ContentHookContext" },
      { name: "content:afterDeleteMany", payload: "ContentRecord[]", context: "ContentManyHookContext" },
      { name: "content:beforePublish", payload: "ContentRecord", context: "ContentHookContext" },
      { name: "content:afterPublish", payload: "ContentRecord", context: "ContentHookContext" },
      { name: "content:beforeUnpublish", payload: "{ id: string }", context: "ContentHookContext" },
      { name: "content:afterUnpublish", payload: "{ id: string }", context: "ContentHookContext" },
      { name: "content:afterUnpublishMany", payload: "ContentRecord[]", context: "ContentManyHookContext" },
    ],
  },
  {
    title: "content read path",
    hooks: [
      { name: "content:beforeRead", payload: "{ id: string }", context: "ContentBeforeReadHookContext" },
      { name: "content:beforeList", payload: "ContentListRequest", context: "ContentBeforeListHookContext" },
      { name: "content:afterRead", payload: "ContentRecord | null", context: "ContentHookContext" },
      { name: "content:afterReadMany", payload: "ContentRecord[]", context: "ContentReadManyHookContext" },
      { name: "content:afterList", payload: "ContentRecord[]", context: "ContentReadManyHookContext" },
    ],
  },
  {
    title: "field-level",
    hooks: [
      { name: "field:beforeValidate", payload: "unknown", context: "FieldHookContext" },
      { name: "field:afterRead", payload: "unknown", context: "FieldHookContext" },
    ],
  },
  {
    title: "content types",
    hooks: [
      { name: "contentType:beforeCreate", payload: "ContentTypeInput", context: "HookContextBase" },
      { name: "contentType:afterCreate", payload: "ContentTypeDefinition", context: "HookContextBase" },
      { name: "contentType:beforeUpdate", payload: "ContentTypeInput", context: "ContentTypeUpdateHookContext" },
      { name: "contentType:afterUpdate", payload: "ContentTypeDefinition", context: "HookContextBase" },
      { name: "contentType:afterDelete", payload: "ContentTypeDefinition", context: "HookContextBase" },
    ],
  },
  {
    title: "assets",
    hooks: [
      { name: "asset:beforeUpload", payload: "{ filename: string; mimeType: string; size: number }", context: "HookContextBase" },
      { name: "asset:afterUpload", payload: "{ id: string }", context: "HookContextBase" },
      { name: "asset:afterDelete", payload: "{ id: string; spaceIds: string[]; size: number }", context: "HookContextBase" },
    ],
  },
  {
    title: "spaces",
    hooks: [
      { name: "space:beforeCreate", payload: "SpaceCreateInput", context: "HookContextBase" },
      { name: "space:beforeLocalesChange", payload: "{ spaceId: string; locales: string[]; previous: string[] }", context: "HookContextBase" },
    ],
  },
  {
    title: "menus",
    hooks: [
      { name: "menu:beforeCreate", payload: "{ spaceId: string; name: string; machineName: string }", context: "HookContextBase" },
      { name: "menu:afterWrite", payload: "{ id: string; spaceId: string }", context: "HookContextBase" },
      { name: "menu:afterDelete", payload: "{ id: string; spaceId: string }", context: "HookContextBase" },
    ],
  },
  {
    title: "members",
    hooks: [
      { name: "member:beforeGrant", payload: "{ spaceId: string; userId: string; role: string; previous: string | null }", context: "HookContextBase" },
      { name: "member:afterGrant", payload: "{ spaceId: string; userId: string; role: string; previous: string | null; mail?: boolean }", context: "HookContextBase" },
    ],
  },
  {
    title: "API keys",
    hooks: [
      { name: "apiKey:beforeIssue", payload: "{ userId: string; name: string; spaceIds: string[] | null; permissions: string[] | null; expiresAt: Date | null }", context: "HookContextBase" },
    ],
  },
  {
    title: "redirects",
    hooks: [
      { name: "redirect:beforeCreate", payload: "{ spaceId: string; locale: string | null; fromPath: string; source: RedirectSource }", context: "HookContextBase" },
    ],
  },
  {
    title: "mail",
    hooks: [
      { name: "mail:afterSend", payload: "{ spaceId: string | null; kind: string; recipients: number; transport: 'instance' | 'account' }", context: "HookContextBase" },
    ],
  },
  {
    title: "requests",
    hooks: [
      { name: "request:served", payload: "RequestServed", context: "HookContextBase" },
    ],
  },
  {
    title: "cache",
    hooks: [
      { name: "cache:purge", payload: "{ tags: string[] }", context: "HookContextBase" },
    ],
  },
];
