/**
 * The SQLite tables as named exports, for drizzle-kit: the instances `sqliteTables`
 * (`../tables.ts`) builds from `../../definitions`, keyed and shaped like `../../schema`.
 */
import { sqliteTables } from '../tables.js';

export const {
  accounts,
  apikeys,
  assetSpaces,
  assetTags,
  assetUsages,
  assetVariants,
  assets,
  auditEntries,
  contentApprovals,
  contentTags,
  contentTypes,
  contentVersions,
  contents,
  controlEvents,
  controlSettings,
  credentials,
  instanceMeta,
  invitations,
  memberships,
  menuItems,
  menus,
  notifications,
  publishedContents,
  pushSubscriptions,
  redirects,
  roles,
  sessions,
  spaceApiHosts,
  spaceEnvironments,
  spaceGroups,
  spacePluginSettings,
  spaces,
  ssoProviders,
  tags,
  twoFactors,
  usageCounters,
  usageExternal,
  usageFlushes,
  userPreferences,
  users,
  verifications,
} = sqliteTables;
