import { isIdentifier, pascalName } from './names.js';
import type { ContentModel, ContentModelField, ContentModelType } from './types.js';

export interface GenerateOptions {
  /** Prepended to each generated interface, e.g. `Manablox`. */
  prefix?: string;
  /** Emitted as a header comment so a reader knows not to hand-edit. */
  source?: string;
}

/** Renders a space's content model as a `.d.ts`. */
export function generateTypes(model: ContentModel, options: GenerateOptions = {}): string {
  const prefix = options.prefix ?? '';
  const contentTypes = model.types.filter((type) => type.kind !== 'block');
  const blockTypes = model.types.filter((type) => type.kind === 'block');

  const lines: string[] = [
    '// Generated by `manablox-sdk types`. Do not edit.',
    ...(options.source ? [`// Source: ${options.source}`] : []),
    '',
    "import type { Asset, Block, BlocksValue, ContentNode, LinkValue } from '@manablox/public-sdk';",
    '',
  ];

  for (const type of [...blockTypes, ...contentTypes]) {
    lines.push(...renderType(type, prefix, model));
    lines.push('');
  }

  if (contentTypes.length > 0) {
    lines.push('/** Every content type in the space, discriminated by `type`. */');
    lines.push(
      `export type ${prefix}Content = ${contentTypes
        .map((type) => pascalName(type.name, prefix))
        .join(' | ')};`,
    );
    lines.push('');
    lines.push('/** Maps a type name to its interface, for `list<ContentByName["page"]>()`. */');
    lines.push(`export interface ${prefix}ContentByName {`);
    for (const type of contentTypes) {
      lines.push(`  ${quoteKey(type.name)}: ${pascalName(type.name, prefix)};`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function renderType(type: ContentModelType, prefix: string, model: ContentModel): string[] {
  const base = type.kind === 'block' ? 'Block' : 'ContentNode';
  const lines = [
    `/** ${type.label} */`,
    `export interface ${pascalName(type.name, prefix)} extends ${base} {`,
    `  type: ${JSON.stringify(type.name)};`,
  ];

  for (const field of type.fields) lines.push(`  ${fieldLine(field, prefix, model)}`);

  lines.push('}');
  return lines;
}

function fieldLine(field: ContentModelField, prefix: string, model: ContentModel): string {
  return `${quoteKey(field.name)}${field.required ? '' : '?'}: ${fieldType(field, prefix, model)};`;
}

/** An item's inline type, its sub-fields rendered like top-level fields. */
function itemType(field: ContentModelField, prefix: string, model: ContentModel): string {
  const fields = (field.fields ?? []).map((sub) => fieldLine(sub, prefix, model));
  return `{ itemId: string; fields: { ${fields.join(' ')} } }`;
}

/** A field's TypeScript type; a relation is an id unless expanded. */
function fieldType(field: ContentModelField, prefix: string, model: ContentModel): string {
  const single = (() => {
    switch (field.kind) {
      case 'scalar':
        return scalarType(field.scalar);
      case 'ref':
        return field.target === 'asset'
          ? 'string | Asset'
          : field.target === 'user'
            ? 'string | { id: string; name: string; image: string | null }'
            : 'string | ContentNode';
      case 'block':
      case 'blockRef':
        return blockUnion(field, prefix, model);
      case 'link':
        return 'LinkValue';
      case 'items':
        return itemType(field, prefix, model);
    }
  })();

  const nullable = field.required ? '' : ' | null';
  // Block lists and template references carry their grid.
  if (field.kind === 'blockRef') return `BlocksValue<${single}>`;
  if (field.kind === 'block') return field.list ? `BlocksValue<${single}>` : `${single}${nullable}`;
  return field.list ? `Array<${single}>` : `${single}${nullable}`;
}

function blockUnion(field: ContentModelField, prefix: string, model: ContentModel): string {
  const names = field.blockTypes?.length
    ? field.blockTypes
    : model.types.filter((type) => type.kind === 'block').map((type) => type.name);

  if (names.length === 0) return 'Block';
  return names.map((name) => pascalName(name, prefix)).join(' | ');
}

function scalarType(scalar: string | undefined): string {
  switch (scalar) {
    case 'Int':
    case 'Float':
      return 'number';
    case 'Boolean':
      return 'boolean';
    case 'DateTime':
      return 'string';
    case 'JSON':
      return 'unknown';
    default:
      return 'string';
  }
}

function quoteKey(name: string): string {
  return isIdentifier(name) ? name : JSON.stringify(name);
}
