import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { main } from '../src/main.js';
import { tempDirs } from './helpers/temp-dir.js';

const fixtures = join(import.meta.dirname, 'fixtures/docs-instance');
const tempDir = tempDirs('manablox-docs-');

afterEach(() => {
  vi.restoreAllMocks();
});

function quiet(): { err: () => string } {
  let err = '';
  vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
  vi.spyOn(process.stderr, 'write').mockImplementation((chunk) => {
    err += String(chunk);
    return true;
  });
  return { err: () => err };
}

async function generate(config = 'manablox.config.ts'): Promise<string> {
  const out = tempDir();
  quiet();
  const code = await main(['docs', 'generate', '--out', out, '--config', join(fixtures, config)]);
  expect(code).toBe(0);
  return out;
}

const read = (out: string, file: string) => readFileSync(join(out, file), 'utf8');

describe('manablox docs generate', () => {
  it('writes the three reference pages with frontmatter and the generated marker', async () => {
    const out = await generate();
    for (const [file, title] of [
      ['reference/errors.md', 'Error keys'],
      ['reference/http-api.md', 'HTTP API reference'],
      ['extending/hooks.md', 'Hooks'],
    ] as const) {
      const text = read(out, file);
      expect(text.startsWith(`---\ntitle: '${title}'\ndescription: '`)).toBe(true);
      expect(text).toContain(
        '<!-- Generated by `manablox docs generate`; edit the source, not this file. -->',
      );
      expect(text.endsWith('\n')).toBe(true);
    }
  });

  it("lists the core's error keys and the config's plugin keys", async () => {
    const out = await generate();
    const errors = read(out, 'reference/errors.md');
    expect(errors).toContain('### `content`');
    expect(errors).toContain('- `content.slug.duplicate`');
    expect(errors).toContain(
      '### `plugins.glossary`\n\n- `plugins.glossary.term.taken`: That term exists already.',
    );
  });

  it("tables the management, delivery and the plugins' procedures", async () => {
    const out = await generate();
    const api = read(out, 'reference/http-api.md');
    expect(api).toContain('## Management API (`/api/v1`)');
    expect(api).toContain('## Delivery API (`/v1`)');
    expect(api).toMatch(
      /\| `POST` \| `\/api\/v1\/plugins\/glossary\/term` \| `spaceId`, `environment\?`, `id` \|/,
    );
  });

  it("reads the hooks from the installed core's hook docs", async () => {
    const out = await generate();
    const hooks = read(out, 'extending/hooks.md');
    expect(hooks).toContain('| Hook | Payload | Context | Transforms |');
    expect(hooks).toMatch(/\| `content:beforeCreate` \| `[^`]+` \| `\w+` \| yes \|/);
  });

  it('needs generate and --out', async () => {
    const { err } = quiet();
    expect(await main(['docs'])).toBe(1);
    expect(await main(['docs', 'build', '--out', tempDir()])).toBe(1);
    expect(await main(['docs', 'generate'])).toBe(1);
    expect(err()).toContain("unknown docs command 'build'");
    expect(err()).toContain('docs generate needs --out <dir>');
  });

  it('refuses a plugin graph the instance would not boot with, writing nothing', async () => {
    const out = tempDir();
    quiet();
    await expect(
      main(['docs', 'generate', '--out', out, '--config', join(fixtures, 'broken.config.ts')]),
    ).rejects.toThrow();
    expect(existsSync(join(out, 'reference'))).toBe(false);
  });
});
