#!/usr/bin/env node
// Writes `tokens.css`: every admin theme token as a reference to the admin's own variable, so
// a prefixed plugin sheet follows the admin's live values. `--check` fails when it is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(pkg, 'package.json'));
const TOKENS = join(pkg, 'tokens.css');

/** Resolved at build time (media and container queries), so copied as values. */
const LITERAL = /^--(breakpoint|container)-/;

/** The `@theme` blocks of `css` with their params and their top-level declarations. */
function themeBlocks(css) {
  const blocks = [];
  for (const match of css.matchAll(/@theme\b([^{]*)\{/g)) {
    let depth = 1;
    let index = match.index + match[0].length;
    const start = index;
    for (; index < css.length && depth > 0; index += 1) {
      if (css[index] === '{') depth += 1;
      else if (css[index] === '}') depth -= 1;
    }
    const body = css.slice(start, index - 1).replace(/\/\*[\s\S]*?\*\//g, '');
    // Drop nested blocks (keyframes) before reading declarations.
    let flat = '';
    let level = 0;
    for (const char of body) {
      if (char === '{') level += 1;
      else if (char === '}') level -= 1;
      else if (level === 0) flat += char;
    }
    const tokens = [];
    for (const decl of flat.matchAll(/(--[\w-]+(?:\\\*)?|--[\w-]+-\*)\s*:\s*([^;]+);/g)) {
      tokens.push([decl[1], decl[2].replace(/\s+/g, ' ').trim()]);
    }
    blocks.push({ params: match[1].trim(), tokens });
  }
  return blocks;
}

/** The admin's theme: Tailwind's defaults with the SDK's tokens over them. */
function adminTheme() {
  const tailwind = readFileSync(require.resolve('tailwindcss/theme.css'), 'utf8');
  const sdk = readFileSync(require.resolve('@manablox/admin-sdk/styles/theme.css'), 'utf8');
  const tokens = new Map();
  for (const { params, tokens: list } of [...themeBlocks(tailwind), ...themeBlocks(sdk)]) {
    // Tailwind's deprecated unnamed defaults (`rounded`, `shadow`); use the named steps.
    if (params.includes('reference')) continue;
    for (const [name, value] of list) {
      if (name.endsWith('-*')) {
        const prefix = name.slice(0, -1);
        for (const key of [...tokens.keys()]) if (key.startsWith(prefix)) tokens.delete(key);
      } else {
        tokens.set(name, value);
      }
    }
  }
  return tokens;
}

function tokensCss() {
  const tokens = adminTheme();
  const lines = [];
  for (const [name, value] of tokens) {
    if (value.includes('--theme(')) continue;
    lines.push(`  ${name}: ${LITERAL.test(name) ? value : `var(${name})`};`);
  }
  return [
    '/* Generated by `pnpm --filter @manablox/admin-plugin tokens`; the admin emits each variable. */',
    '@theme {',
    ...lines,
    '}',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = tokensCss();
  if (process.argv.includes('--check')) {
    if (readFileSync(TOKENS, 'utf8') !== next) {
      console.error('tokens.css is stale; run `pnpm --filter @manablox/admin-plugin tokens`');
      process.exit(1);
    }
    console.log('tokens.css up to date');
  } else {
    writeFileSync(TOKENS, next);
    console.log('wrote tokens.css');
  }
}
