/**
 * The Postgres tables as named exports, for drizzle-kit and importers; the same instances as
 * `postgresTables` (`../tables.ts`), which builds them from `../definitions`.
 */
import { postgresTables } from '../tables.js';

export const {
  accounts,
  apikeys,
  assetSpaces,
  assetTags,
  assetUsages,
  assetVariants,
  assets,
  auditEntries,
  contentApprovals,
  contentTags,
  contentTypes,
  contentVersions,
  contents,
  controlEvents,
  controlSettings,
  credentials,
  instanceMeta,
  invitations,
  memberships,
  menuItems,
  menus,
  notifications,
  publishedContents,
  pushSubscriptions,
  redirects,
  roles,
  sessions,
  spaceApiHosts,
  spaceEnvironments,
  spaceGroups,
  spacePluginSettings,
  spaces,
  ssoProviders,
  tags,
  twoFactors,
  usageCounters,
  usageExternal,
  usageFlushes,
  userPreferences,
  users,
  verifications,
} = postgresTables;
